### ISSUE TITLE
Improve redirects for old documentation links

### ISSUE THREAD

**Issue by rmarscher** [apollographql/tools-docs#10]
Hi. Sorry, this probably isn't the best place to report this. You don't need to keep it open. I just wanted to let you know in case you weren't aware.

I was searching for how to implement a JSON scalar type on google using the search terms "apollo data json type." The first hit is a link to http://docs.apollostack.com/apollo-server/scalars.html which is returning a 301 redirect to //dev.apollodata.com/core/. It would be better if it redirected to http://dev.apollodata.com/tools/graphql-tools/scalars.html

**Comment by drFabio** [comment]
Maybe somewhat related the link http://docs.apollostack.com/apollo-server/resolvers.html [here](http://dev.apollodata.com/tools/graphql-tools/generate-schema.html) on:

> resolvers is a required argument and should be an object that follows the pattern explained in the guide section on resolvers.

Is redirecting to http://dev.apollodata.com/core/

**Comment by helfer** [comment]
Yeah, that link appears broken because we moved the docs recently. It would be awesome if you could fix it with a PR!

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

Docs can be found live at apollographql.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
