### ISSUE TITLE
update docs as SubscriptionServer is deprecated from subscriptions-transport-ws

### ISSUE THREAD

**Issue by farzd** [apollographql/tools-docs#121]
Hey Guys,
is it possible to update the docs for the new update in https://github.com/apollographql/subscriptions-transport-ws

this page http://dev.apollodata.com/tools/graphql-subscriptions/lifecycle-events.html
is referencing a deprecated API

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

Docs can be found live at apollographql.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

Docs can be found live at apollographql.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
