### ISSUE TITLE
Launchpad in 'Generating a Schema' section is broken locally

### ISSUE THREAD

**Issue by KSuttle-cng** [apollographql/tools-docs#132]
Not sure if this is the place to report this, but when you download the launchpad linked to from:   http://dev.apollodata.com/tools/graphql-tools/generate-schema.html

https://launchpad.graphql.com/1jzxrj179

The GraphiQL result pane immediately shows
```
Invalid options provided to ApolloServer: (0 , _schema.context) is not a function
```

Let me know if this is more appropriate to report elsewhere. Thanks.

**Comment by stubailo** [comment]
Can you file an issue here please? https://github.com/apollographql/launchpad

Thanks!

**Comment by KSuttle-cng** [comment]
Sure thing. Thanks @stubailo.

**Comment by KSuttle-cng** [comment]
Already reported: https://github.com/apollographql/launchpad/issues/59

**Comment by stubailo** [comment]
Thanks!
