### ISSUE TITLE
Production deployment recommendations

### ISSUE THREAD

**Issue by sandervanhooft** [apollographql/tools-docs#36]
This is a repost from https://github.com/apollostack/graphql-server/issues/212 as suggested by @rohanray. I agree it would be great to have this documented.

> Hi all,
> 
> How are you building and deploying graphql-server-express to Production? I can't find anything on this in the server docs.
> 
> Kind regards,
> 
> Sander

**Comment by helfer** [comment]
@sandervanhooft we have a pretty custom setup for Galaxy and Optics, but if someone else would write a guide, I definitely think we should include it here!

**Comment by stubailo** [comment]
I think it's about the same as any other Node.js app, Meteor if you're using that to build and deploy. Perhaps we can link to some existing tutorial about deploying Node apps?

**Comment by marciobueno1** [comment]
@stubailo, is there some tutorial about deplyoing Node apps that you recommend? I intend to use the graphql-server-express on dokku.

**Comment by stubailo** [comment]
Sorry, I don't have any recommendations - I don't think we want to be in the business of recommending particular deployment solutions for Node servers.
