### ISSUE TITLE
more complete modular schema and resolver definitions example

### ISSUE THREAD

**Issue by joefraley** [apollographql/tools-docs#41]
It would be really nice to see this section fleshed out a bit more (it's one of the most confusing things about organizing a GraphQL project).

In the current demo:

```javascript
// schema.js
import Author from './author.js'; // just some type

const RootQuery = `
  type RootQuery {
    author(name: String): Author // only one query defined here.
  }
`;

const SchemaDefinition = `
  schema {
    query: RootQuery
  }
`;

export default makeExecutableSchema({
  typeDefs: [SchemaDefinition, RootQuery, Author],
  resolvers: {},
});
```

but I'm still confused about the best way to combine Query definitions. For example, consider this extension:

```javascript
// schema.js
import {Author, AuthorQuery} from './author.js';
import {User, UserQuery} from './user.js';

export default makeExecutableSchema({
  typeDefs: [Author, AuthorQuery, User, UserQuery], // it feels like this should be possible
  resolvers: {}, // same story for resolvers...
});
```

Is this a pattern/architecture to avoid? If so, I think that could be spelled out. If not, I think a working example could be expanded.

What's the use-case for this pattern? The case where you define lots of resolve methods for different types to allow resolving by different parameters (get all users with image, get all users by sign-up date, get all users with certain setting on). Having lots of accessible resolves means: long resolve file, and long query type. It's lame for all of it to live in one huge file.

**Comment by helfer** [comment]
@joefraley I think there's an ongoing discussion on the graphql-tools repo about how best to split a schema. Your idea is very similar to some other ideas there, so I think we should try to move graphql-tools in that direction and make the schema more composable. We were planning to do so from the start, but never really got around to it. If you're interested in it, you could make a concrete proposal on the graphql-tools repo, and start implementing it after a discussion. I don't think it should be too hard.

**Comment by joefraley** [comment]
@helfer sure that makes sense. It looks like there's a similar discussion going on here: https://github.com/apollostack/graphql-tools/issues/186.

`graphql-merge` is pretty much exactly what I imagine happening under the hood for `graphql-tools`: https://github.com/liamcurry/gql/tree/master/packages/gql-merge

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

Docs can be found live at apollographql.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
