### ISSUE TITLE
Documentation for mocking

### ISSUE THREAD

**Issue by plm75** [apollographql/tools-docs#45]
Hello, thanks for the great work.

Documentation about mocking is a little confusing because it shows examples and methods that are very different from this [post](https://dev-blog.apollodata.com/mocking-your-server-with-just-one-line-of-code-692feda6e9cd#.bj5v0o8fb) which is referenced in the documentation.

For instance what's up with `mockServer` ? Is this deprecated and if so why is still available in `graphql-tools` ?  Maybe the link to the blog post should be qualified for the fact that the code is outdated ?

**Comment by helfer** [comment]
@plm75 yes, I think you're right. The code in the blog post should still work mostly, and `mockServer` hasn't been deprecated as far as I know (we just don't use it ourselves). If you have specific improvements, please feel free to open a PR!

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

Docs can be found live at apollographql.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
