### ISSUE TITLE
typeDefs can be a string in makeExecutableSchema

### ISSUE THREAD

**Issue by pjarts** [apollographql/tools-docs#46]
The documentation says: "typeDefs is a required argument and should be an array of GraphQL schema language strings or a function that takes no arguments and returns an array of GraphQL schema language strings". But according to the comments in the code and your "frontpage-server" example on GitHub, typeDefs can be a single string that contains all type definitions for the schema.

**Comment by helfer** [comment]
@pjarts that is correct. IIRC I decided not to mention that to make things a bit simpler in the docs. I'd be happy to take a PR that mentions that strings are also allowed.

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

Docs can be found live at apollographql.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
