### ISSUE TITLE
TOC nav issue with multiple "Installing" sections

### ISSUE THREAD

**Issue by funkyeah** [apollographql/tools-docs#67]
When in the installing docs section for GraphQL Server the "Installing" line is highlighted in both that section and the `Subscriptions` section:

![image](https://cloud.githubusercontent.com/assets/469403/24268564/2719522a-0fdc-11e7-92e9-e140bc68166e.png)

Minor annoyance, but I believe the root issue also causes the footer nav to be wrong for the GraphQL Server section. At the end of both Installing sections the previous/next is relative to the Subscriptions Installing section only:

![image](https://cloud.githubusercontent.com/assets/469403/24268696/9e621ba0-0fdc-11e7-9877-80363383859f.png)

**Comment by helfer** [comment]
Thanks for bringing this to our attention @funkyeah! This seems to be an issue with hexo. I think the only way to change it would be to give the second one a different title. I've changed it to "Installation", let's see if it helps...

**Comment by funkyeah** [comment]
Looks like you are probably right, nav works for me with different titles.
