### ISSUE TITLE
ERROR Local hexo not found when trying to run locally

### ISSUE THREAD

**Issue by p4bloch** [apollographql/tools-docs#70]
I tried to run the docs locally but somehow hexo is not finding how to start itself. Couldn't find an issue in hexo with information about this.

Tried installing `hexo` and `hexo-cli` globally, but it still fails.

**Steps to reproduce**
1. clone the repo
2. follow steps provided in the README
3. you should get `ERROR Local hexo not found in ~/project/folder` when running npm start

Node and npm versions (through nvm)
```sh
$ node -v
v7.5.0

 $ npm -v
4.1.2
```

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

Docs can be found live at apollographql.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
