### ISSUE TITLE
Error handling and logging section

### ISSUE THREAD

**Issue by pnevyk** [apollographql/tools-docs#72]
First of all, in error handling section there is a reference about `forbidUndefinedInResolve` which isn't anywhere in the source code of `graphql-tools` (and hence its import causes the error). I think the correct way how to achieve intended behavior is to set `allowUndefinedInResolve` property in `makeExecutableSchema` function call to `false`.

Second, one doesn't have to call `addErrorLoggingToSchema` directly since it is called in `_generateSchema` if a logger is passed to `makeExecutableSchema`. Isn't it cleaner solution to just pass a logger? Or is this functionality already deprecated in favour of `formatError` option?

I am willing to make a PR, I just need to clarify a few things for myself:
* Am I right that functionality described in `forbidUndefinedInResolve` should be achieved using `allowUndefinedInResolve` property?
* Is `formatError` already recommended instead of `addErrorLoggingToSchema`? Or if it isn't, is it better to just pass a logger to trigger this functionality instead of explicitly call `addErrorLoggingToSchema`?

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

Docs can be found live at apollographql.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
