### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by lucasconstantino** [apollographql/tools-docs#74]
Hello there. I've executed a [broken-link-checker](https://github.com/stevenvachon/broken-link-checker) against this documentation. Here goes what I've found:

```sh
http://dev.apollodata.com/angular - (HTTP_403)
http://dev.apollodata.com/tools/graphql-tools/tools/graphql-tools/mocking.html#addMockFunctionsToSchema - (HTTP_403)
http://dev.apollodata.com/tools/graphql-server/migration-hapi.md - (HTTP_403)
http://dev.apollodata.com/tools/graphql-server/migration.md - (HTTP_403)
http://dev.apollodata.com/angular - (HTTP_403)
http://dev.apollodata.com/react/example-schema.md - (HTTP_403)
http://dev.apollodata.com/tools/graphql-server/subscriptions.html#authentication - (HTTP_403)
http://info.meteor.com/blog/optimistic-ui-with-meteor-latency-compensation - (HTTP_409)
http://dev.apollodata.com/angular - (HTTP_403)
```

**Comment by helfer** [comment]
Thanks! We still have to figure out where those links are though...

http://dev.apollodata.com/tools/graphql-server/subscriptions.html#authentication is at the bottom of this page: http://dev.apollodata.com/react/subscriptions.html#subscribe-to-more

How do we track down the others?

**Comment by theadactyl** [comment]
Closing this issue as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

Docs can be found live at apollographql.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

If this is still a problem in the new docs we'd appreciate you opening a new issue in the corresponding repo. Thanks! 🙏
